package:
  name: <%= name %>
github:
  username: <%= github.username %>
  repository: <%= github.repository %>
workInProgress: true
credits: []
copyright:
  year: <%= year %>
  author: <%= author.name %>
  url: <%= author.url %>
example:
